channels:
  - conda-forge

dependencies:
  - pandoc
  - ipykernel
  - pip
  - pip:
    - sphinx==5.3.0
    - sphinx-autodoc-typehints==1.18.1
    - sphinx-rtd-theme==1.0.0
    - sphinx-rtd-size==0.2.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - sphinx-mdinclude==0.5.3
    - nbsphinx==0.8.9
    - sphinx-gallery==0.11.1